/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '../src',
    files: '**/*.stories.?(ts|tsx)',
    importPathMatcher: /\.stories\.(ts|tsx)$/,
    // @ts-ignore — require.context is provided by the Metro bundler plugin
    req: require.context('../src', true, /\.stories\.(ts|tsx)$/),
  },
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require('@storybook/react-native/preview'),
  require('./preview'),
];

globalThis.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
